name: Gerar animação

on:
  # Executar a cada 12 horas
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

  push:
    branches:
      - main


jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate contribuicoes-github-animacao-cobrinha.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: franklin-albuquerque
          outputs: |
            dist/contribuicoes-github-animacao-cobrinha.svg
            dist/contribuicoes-github-animacao-cobrinha-dark.svg?palette=github-dark

      - name: push contribuicoes-github-animacao-cobrinha.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
