name: Animação do gráfico de contribuições

on:
  # Atualiza a cada 48 horas
  schedule:
    - cron: "* */48 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Importar chave GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@master
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          fingerprint: '5651FBC1E2185D99535F3172BAA2713318B6B349'
          git_user_signingkey: true
          git_commit_gpgsign: true
      -
        name: Gerar animação da cobrinha
        uses: Platane/snk/svg-only@main
        with:
          github_user_name: franklin-albuquerque
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      -
        name: Enviar alterações
        uses: crazy-max/ghaction-github-pages@dev
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
