name: Gerar animação

on:
  # Atualizar a cada 6 horas
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: action/checkout@v2

      - name: Gerar contribuicoes-github-animacao-cobrinha.svg
        uses: Platane/snk@master
        with:
          github_user_name: franklin-albuquerque
          outputs: |
            dist/contribuicoes-github-animacao-cobrinha.svg
            dist/contribuicoes-github-animacao-cobrinha-dark.svg?palette=github-dark

      - run: git status

      - name: Enviar alterações
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Enviar contribuicoes-github-animacao-cobrinha.svg para o branch main
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
