name: Gerar animação

on:
  # Executar a cada 12 horas
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v2.2.1
        id: snake-gif
        with:
          github_user_name: franklin-albuquerque
          svg_out_path: dist/contribuicoes-github-animacao-cobrinha.svg

      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
