name: Gerar animação

on:
  # Atualizar a cada 6 horas
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@main

      - name: Gerar animação do gráfico de contribuições
        uses: Platane/snk/svg-only@main
        with:
          github_user_name: franklin-albuquerque
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Enviar github-contribution-grid-snake.svg para o branch output
        uses: crazy-max/ghaction-github-pages@dev
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
